In [2]:
import nflreadpy as nfl
import pandas as pd

pd.set_option("display.max_columns", None)

import os
import django

os.environ.setdefault(
    "DJANGO_SETTINGS_MODULE", "backend.doritostats.settings"
)  # Adjust if your settings module is different
django.setup()

In [4]:
year = 2025

In [8]:
from backend.playoff_pool.players import get_all_playoff_players


playoff_players = get_all_playoff_players(year=year)
playoff_players

/Users/desipilla/Documents/GitHub/espn-api-v3/backend/playoff_pool/players.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playoff_team_stats["fantasy_points"] = playoff_team_stats.apply(

        gsis_id   player_id         full_name team position  fantasy_points
77   00-0032726  00-0032726  Ka'imi Fairbairn  HOU        K           321.0
39   00-0031492  00-0031492       Jason Myers  SEA        K           315.0
544  00-0037224  00-0037224    Cameron Dicker  LAC        K           280.0
900  00-0039409  00-0039409        Cam Little  JAX        K           245.5
30   00-0031136  00-0031136     Chris Boswell  PIT        K           226.0
..          ...         ...               ...  ...      ...             ...
9            NE          NE           NE D/ST   NE      DST           108.0
10          PHI         PHI          PHI D/ST  PHI      DST           110.0
11          PIT         PIT          PIT D/ST  PIT      DST           124.0
12          SEA         SEA          SEA D/ST  SEA      DST           143.0
13           SF          SF           SF D/ST   SF      DST            62.0

[459 rows x 6 columns]

In [21]:
playoff_players

        gsis_id   player_id         full_name team position  fantasy_points
77   00-0032726  00-0032726  Ka'imi Fairbairn  HOU        K           321.0
39   00-0031492  00-0031492       Jason Myers  SEA        K           315.0
544  00-0037224  00-0037224    Cameron Dicker  LAC        K           280.0
900  00-0039409  00-0039409        Cam Little  JAX        K           245.5
30   00-0031136  00-0031136     Chris Boswell  PIT        K           226.0
..          ...         ...               ...  ...      ...             ...
9            NE          NE           NE D/ST   NE      DST           108.0
10          PHI         PHI          PHI D/ST  PHI      DST           110.0
11          PIT         PIT          PIT D/ST  PIT      DST           124.0
12          SEA         SEA          SEA D/ST  SEA      DST           143.0
13           SF          SF           SF D/ST   SF      DST            62.0

[459 rows x 6 columns]

In [ ]:
from backend.playoff_pool.players import PLAYOFF_TEAMS

set(PLAYOFF_TEAMS[year]) - set(playoff_players["team"].unique())

set()

In [ ]:
from asgiref.sync import sync_to_async
from backend.playoff_pool.players import upload_playoff_players_to_db

positions_to_keep = [
    "QB",
    "K",
    "DE",
    "P",
    "OT",
    "OLB",
    "DT",
    "LB",
    "MLB",
    "G",
    "LS",
    "FB",
    "WR",
    "TE",
    "CB",
    "NT",
    "S",
    "SAF",
    "RB",
    "FS",
    "DB",
    "ILB",
    "C",
    "DL",
    "OL",
    "DST"
]

year = 2024
await sync_to_async(upload_playoff_players_to_db)(
    year=year, positions_to_keep=positions_to_keep
)

/Users/desipilla/Documents/GitHub/espn-api-v3/backend/playoff_pool/players.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playoff_team_stats["fantasy_points"] = playoff_team_stats.apply(

14

In [20]:
player_stats = nfl.load_player_stats([2025]).to_pandas()
player_stats[player_stats["week"] == 18]
sorted(player_stats.position.dropna().unique().tolist())

['C',
 'CB',
 'DB',
 'DE',
 'DL',
 'DT',
 'FB',
 'FS',
 'G',
 'ILB',
 'K',
 'LB',
 'LS',
 'MLB',
 'NT',
 'OL',
 'OLB',
 'OT',
 'P',
 'QB',
 'RB',
 'S',
 'SAF',
 'TE',
 'WR']